### ISSUE TITLE
Can't pass options to create_collection

### ISSUE THREAD

**Issue by bittersweet** [bcg/em-mongo#34]
Currently you cannot pass options to the [create_collection](https://github.com/bcg/em-mongo/blob/master/lib/em-mongo/database.rb#L117) command. 

This is mentioned in the documentation but that might be something left over from the regular Ruby [Mongo driver](https://github.com/mongodb/mongo-ruby-driver/blob/master/lib/mongo/db.rb#L278)

Is this by choice or should I try adding this to submit a pull request?

**Comment by dCSeven** [comment]
Merged it (but it has already been included in #46)
