### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by georgeu2000** [bcg/em-mongo#57]
I ran the example and it does not seem to work on Ruby 2.5.1 and MongoDB 3.6.2.

Is there any documentation on how to make it work?

**Comment by georgeu2000** [comment]
On my Mac (10.13.4) have to do `EM::Mongo::Connection.new('0.0.0.0')`. `localhost` does not work.

**Comment by dCSeven** [comment]
Yeah, I'm sorry that I'm writing that late, but this month is test month at the university, so I don't have a lot of free time for anything.

Unfortunately the example is not really tested by me. If it isn't working I'll change it when I've got more time.
The rest of the project is working fine though, so if you read the documentation I think everything should be clear (ask if it isn't).
