### ISSUE TITLE
Publish 0.6.0 via rubygems.org

### ISSUE THREAD

**Issue by hupfis** [bcg/em-mongo#58]
Thanks for this great gem - could you please make the latest verison available via rubygems.org as well?
Thanks, Dominik

**Comment by dCSeven** [comment]
@bcg since I don't have any access to the rubygems site, could you please push it there (or give me the rights to do that)?

**Comment by bcg** [comment]
@dCSeven sure, what is your email address on rubygems.org?

**Comment by bcg** [comment]
Or email me your RubyGems account info and I will get you setup.

**Comment by bcg** [comment]
```
$ rake gem:release
Pushing gem to https://rubygems.org...
Successfully registered gem: em-mongo (0.6.0)
$
```
https://rubygems.org/gems/em-mongo/versions/0.6.0
